### PR TITLE
Feature/consent to treatment

### PR DESCRIPTION
**Pull request by declankieran-nhsd**
@vickyjaiswal0308 @marcusfearnett-nhsdigital For review

I've added a guidance page for consent, with one example.  I think we need to discuss the code for the others, I've put a few placeholders in with TODOs for other possible examples.  Page in question

https://declankieran-nhsd.github.io/ra-sandbox/consent-to-treatment.html

### CODE REVIEW

**Comment by declankieran-nhsd** [comment]
@ed-bright @marcusfearnett-nhsdigital 

I've changed the guidance to correct referencing 'consent to treatment' as the primary guidance to just reference the mental health capacity act and the caldicott principles in the scope of sharing information.  The statement 'according to existing guidance and best practice.' is taken directly from the previous requirements doc.

I've also changed the interaction pattern to reflect the absence of a consent indicating a patient's dissent to sharing the information as discussed yesterday.  However I did find these requirements in the document @marcusfearnett-nhsdigital provided.

```
RAU019
Cannot delete consent status from an existing Reasonable Adjustment Flag record
It MUST not be possible for a user to delete the consent status associated with an existing Reasonable Adjustment Flag record.

RAO010
Patient dissent
It MUST be possible to record that a patient does not consent to having a Reasonable Adjustment record.
```

Which would suggest maintaining the consent state, i.e. updating rather than removing the Consent resource each time a patient revoked their consent.

The example has been updated to show examples of how to use the extensions and with an example of using the policyRule elect, which is bound to the proxyRole valueset.  This is the only example needed given no consent is implied by the absence of a consent resource, which seems like a bad pattern for implementation given it will need to be handled differently for consent not previously given, actual dissent and possibly revoked consent, as opposed to just examining the state of the consent object.

CC: @vickyjaiswal0308 

Can be access on the gh page (link different from previous)

https://declankieran-nhsd.github.io/ra-sandbox/consent-to-share-information.html

**Comment by ed-bright** [comment]
@declankieran-nhsd That Consent JSON example with the extensions is great thank you - look forward to seeing the updated ones for the other resources too

**Comment by ed-bright** [comment]
@declankieran-nhsd

Just a small correction - the category should be the MasterFlag category something like
system: "https://fhir.nhs.uk/England/CodeSystem/PatientFlagCategory"
code: "001":
display: "Reasonable Adjustments"

As this is a consent for the Flag as a whole to be stored, not for each individual adjustment

**Review by marcusfearnett-nhsdigital — CHANGES_REQUESTED** [review]
OK. Review comments as discussed...
  1 If we want to record Consent not given (i.e. Dissent to share)
  we'd just do Create Consent with "status" : "rejected"
  & optionally in "https://fhir.nhs.uk/England/StructureDefinition/Extension-ConsentCreateSummary"
  something like "text" : "Patient declined to share reasonable adjustment information"
  
  This'd then feed into updated System Interaction blurb, seq. diagram (https://github.com/declankieran-nhsd/ra-sandbox/blob/feature/consent-to-treatment/input/images-source/consent-sequence.plantuml) and 'Consent is not given' Example
  
  2 Illustration to Diagram
  
  3 In Workflow bpmn, isn't the capacity decision by the Practitioner?

  4 text element - can we get rid?

Working up proposal as new branch /consent-to-share-mf

**Comment by declankieran-nhsd** [comment]
> @declankieran-nhsd
> 
> Just a small correction - the category should be the MasterFlag category something like system: "https://fhir.nhs.uk/England/CodeSystem/PatientFlagCategory" code: "001": display: "Reasonable Adjustments"
> 
> As this is a consent for the Flag as a whole to be stored, not for each individual adjustment

@ed-bright 

Seems like there is maybe some work on the codesystem still to be done, you can look at what is currently there at

https://declankieran-nhsd.github.io/ra-sandbox/artifacts.html

In the Code Systems section.  There is this CodeSystem that appears to suggest it would be used for Consent, but it isn't used anywhere.  Should this maybe be removed?

The CodeSystem being used here (should probably be renamed RA-MasterFlagCategory.)

https://declankieran-nhsd.github.io/ra-sandbox/CodeSystem-RA-FlagCategory.html

Seemed suggest to me that the consent was giving at a programme level, i.e. RA, CP-IS, FGM etc...  If its at the adjustment level and from the code you've given, it seems like maybe this is the CodeSystem that should be used?

https://declankieran-nhsd.github.io/ra-sandbox/CodeSystem-RA-AdjustmentCategory.html

I can change in the example no problem, and the logic still holds for the interaction diagram (which will be changed now it is agreed the consent object will maintain the state of patient consent in terms of given or not given)

**Comment by declankieran-nhsd** [comment]
> OK. Review comments as discussed... 1 If we want to record Consent not given (i.e. Dissent to share) we'd just do Create Consent with "status" : "rejected" & optionally in "https://fhir.nhs.uk/England/StructureDefinition/Extension-ConsentCreateSummary" something like "text" : "Patient declined to share reasonable adjustment information"
> 
> This'd then feed into updated System Interaction blurb, seq. diagram (https://github.com/declankieran-nhsd/ra-sandbox/blob/feature/consent-to-treatment/input/images-source/consent-sequence.plantuml) and 'Consent is not given' Example
> 
> 2 Illustration to Diagram
> 
> 3 In Workflow bpmn, isn't the capacity decision by the Practitioner?
> 
> 4 text element - can we get rid?
> 
> Working up proposal as new branch /consent-to-share-mf

I would suggest using `inactive` rather than `rejected` to stay aligned with the R5 version

https://www.hl7.org/fhir/valueset-consent-state-codes.html

**Comment by declankieran-nhsd** [comment]
@ed-bright @marcusfearnett-nhsdigital 

Should we be using these codes in the valuesets or has this already been review, and if so where?

https://digital.nhs.uk/services/reasonable-adjustment-flag/impairment-and-adjustment-codes

Just looking at the consent codes 

https://digital.nhs.uk/services/reasonable-adjustment-flag/impairment-and-adjustment-codes#consent-and-review-codes

I think the base binding in consent.scope element possibly covers what this is trying to convery, at least with consent given and declined consent (valuset in question http://hl7.org/fhir/R4/valueset-consent-scope.html).  Using the status, i.e. `active` or `inactive` covers the first two

The code 

1833271000000103 	Review of Reasonable Adjustments needs (procedure)

doesn't really fit this though.  Looking at the requirements document there are a couple of mentions of review, e.g.

> Existing business processes will provide opportunities to create and or review Flags; such as at new patient registration, annual health check, new diagnosis etc.

I think this would be better handled with a Task resource as you can set a time on that, the code doesn't conceptually fit with the actual Consent object, assuming this is still a requirement...

**Comment by declankieran-nhsd** [comment]
@marcusfearnett-nhsdigital is looking to do the changes outstanding here in a separate branch.  Just merging this in with the other PR, sp the amount of change isn't completely huge in one PR

**Pull request merged**
